modLoader = "javafml"
loaderVersion = "[${forge_version},)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "create_lt"
version = "${version}"
displayName = "Create: Less Ticking"
authors = "Dadamalda"
description = '''
A tiny performance mod, decreasing the rate some Create components tick at
'''
logoFile = "icon.png"

[[dependencies.create_lt]]
modId = "forge"
mandatory = true
versionRange = "[${forge_version},)"
ordering = "NONE"
side = "SERVER"

[[dependencies.create_lt]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version}"
ordering = "NONE"
side = "SERVER"

[[dependencies.create_lt]]
modId="create"
mandatory=true
versionRange="*"
ordering="NONE"
side="SERVER"
